apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: onlineboutique-prod

labels:
  - pairs:
      app.kubernetes.io/part-of: onlineboutique
      app.kubernetes.io/managed-by: kustomize
      env: prod

replicas:
  - name: adservice
    count: 2
  - name: cartservice
    count: 3
  - name: checkoutservice
    count: 3
  - name: currencyservice
    count: 3
  - name: emailservice
    count: 2
  - name: frontend
    count: 3
  - name: loadgenerator
    count: 0
  - name: paymentservice
    count: 3
  - name: productcatalogservice
    count: 3
  - name: recommendationservice
    count: 3
  - name: shippingservice
    count: 3

