apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: onlineboutique-staging

labels:
  - pairs:
      app.kubernetes.io/part-of: onlineboutique
      app.kubernetes.io/managed-by: kustomize
      env: staging

replicas:
  - name: frontend
    count: 2
  # Service thứ 2 tạm thời giữ replica = 1 (các service khác sẽ scale về 0)
  - name: cartservice
    count: 1
  - name: adservice
    count: 0
  - name: checkoutservice
    count: 0
  - name: currencyservice
    count: 0
  - name: emailservice
    count: 0
  - name: loadgenerator
    count: 0
  - name: paymentservice
    count: 0
  - name: productcatalogservice
    count: 0
  - name: recommendationservice
    count: 0
  - name: shippingservice
    count: 0

