apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devs-edit
  namespace: onlineboutique-dev
subjects:
- kind: Group
  name: onlineboutique-devs
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-view
  namespace: onlineboutique-dev
subjects:
- kind: Group
  name: onlineboutique-qa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-admin
  namespace: onlineboutique-dev
subjects:
- kind: Group
  name: onlineboutique-devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

