apiVersion: v1
kind: Namespace
metadata:
  name: onlineboutique-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: onlineboutique-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: onlineboutique-prod

