apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlineboutique-staging
  namespace: argocd
spec:
  project: onlineboutique
  source:
    repoURL: https://github.com/<org>/<manifests-repo>.git
    targetRevision: env/staging
    path: kustomize/environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

